Add Tests, Demo Page, CSV -> JSON Conversion and Downloads, and a pull request template.
coston/json-to-csv-export pull request #19
Opened 2022-02-07 19:52 UTC by bvdalling

This provides some tests that are set up and passing. This also provides a simple demo page under "demo/index.html". Included in this is the ability to convert back from CSV to JSON and download it. 

## Major changes:
* moved the json -> csv conversion from the download function and into it's own jsonToCsv function. This should make it easy to use this package for conversions and downloads.
* added a new download function that preps the page and performs the download operation.
* added csv -> json conversion to make it simple to reverse and test the initial conversion. 

## Support
I made sure to support previous use-cases of the csvDownload function. Any previous implmentation *should* still work.

2022-02-08 01:20 UTC, coston requested changes
@bvdalling very nice features! Please conform to the existing style/setup of the repo. Otherwise, it's more appropriate to propose style changes before opening a PR. 

I've requested 3 groups of changes:
- No variable reassignments
- Remove irrelevant code and files
- Contribute to the existing demo site

Lastly, please update the readme documentation. Thank you for this contribution!

2022-02-08 01:20 UTC, coston commented on .vscode/settings.json
> +}
This does not belong in the project.

2022-02-08 01:20 UTC, coston commented on .github/pull-request-template.md
> +## Description
Out of scope, but I'll take it.

2022-02-08 01:20 UTC, coston commented on demo/index.html
> +<html>
Please build upon the existing demo, found in `/docs`

2022-02-08 01:20 UTC, coston commented on package.json
> +    "test": "jest",
Nice!

2022-02-08 01:20 UTC, coston commented on src/index.js
> +export const jsonToCsv = (__data, __name, __delimiter) => {
nit: I'm not a fan of underscore prefixes for regular args

2022-02-08 01:20 UTC, coston commented on src/index.js
> +        let schema = {}
One of the two `schema` is unused

2022-02-08 01:20 UTC, coston commented on src/index.js
> +  }
minor: could you rewrite these new functions to be without reassignments? I prefer the code style here to be functional.

2022-02-08 01:20 UTC, coston commented on test/jsonToCSv.test.js
> +// test('we have the correct csv data', () => expect(csvString.trim()).toBe(validCsv)) // TODO [BD|02/07/2022] Figure out why the CSV output is always failing.
Note to self, if you don't fix it first

2022-02-08 14:45 UTC, bvdalling commented
I'll get on these suggested changes sometime soon.

2022-02-08 16:09 UTC, coston commented on src/index.js
> +export const jsonToCsv = (__data, __name, __delimiter) => {
It would be advantageous to make all the new function args named parameters for ease of use. (E.g. no name override, but a delimiter.)

2022-02-09 16:53 UTC, bvdalling commented on .github/pull-request-template.md
> +## Description
I can remove this. I just noticed you had no formal PR template.

2022-02-09 16:54 UTC, bvdalling commented on .vscode/settings.json
> +}
This has been removed.

2022-02-10 00:37 UTC, coston requested changes
There's still opportunity for improvements
2. Update the readme
2. Update the demo/readme docs to be more concise. People don't like to read.
3. Update the demo to contain demos of all the new features.
4. Consider not even exporting/documenting the download function, for simplicity.

2022-02-10 00:37 UTC, coston commented on docs/index.mdx
> +    Download JSON Data
Good

2022-02-10 00:37 UTC, coston commented on docs/index.mdx
> +```
All of these void return blocks are unnecessary in the docs.

2022-02-10 00:37 UTC, coston commented on docs/index.mdx
> +
this one is fine. Maybe it would be best in a <details><summary>summary block</summary>
contents
</details>

2022-02-10 00:37 UTC, coston commented on docs/mockData.js
> +export const jsonData = mockData
```suggestion
export default jsonData
```

2022-02-10 00:37 UTC, coston commented on docs/index.mdx
> +| 3   | delimiter | `string` | `optional`  | ","            | field separator             |
Four of these functions have the same arguments. The docs can be simplified to reflect that.

2022-02-10 00:37 UTC, coston commented on docs/root.js
> +    </div>
Try not to commit stuff like this. There's no prettier config in this repo, but there is a format script to align with the project style.

2022-02-10 00:37 UTC, coston commented on test/jsonToCSv.test.js
> +// test('we have the correct csv data', () => expect(csvString.trim()).toBe(validCsv)) // TODO [BD|02/07/2022] Figure out why the CSV output is always failing.
You can do it, @bvdalling

2022-02-10 00:59 UTC, coston commented on src/index.js
> +    object: object,
This isn't an object
```suggestion
    data,
```

2022-02-10 01:00 UTC, coston commented on src/index.js
> +    filename: filename,
What's the point of returning the filename, when we already have it in the args?

2022-02-10 01:02 UTC, coston commented on .github/pull-request-template.md
> +## Description
It can stay

2022-02-10 01:06 UTC, coston commented on src/index.js
> +    object: object,
```suggestion
    data: object,
```

2022-09-13 22:46 UTC, coston commented
Thank you for the work on this @bvdalling! The main features of this PR were covered by #30 and are available in [v2.0.0](https://github.com/coston/json-to-csv-export/releases/tag/v2.0.0)

2022-09-13 22:46 UTC, coston commented
Thank you for the work on this @bvdalling! The main features of this PR were covered by #30 and are available in [v2.0.0](https://github.com/coston/json-to-csv-export/releases/tag/v2.0.0)

2022-09-13 22:46 UTC, closed without merging