Updating the lib to TS + changed signature
coston/json-to-csv-export pull request #30
Opened 2022-08-15 13:39 UTC by dnim

Resolves #27 

I still a bit didn't get how is better to update doc generation. Will be very glad for any help or comments

2022-08-16 21:21 UTC, coston commented
Hey @dnim! Thank you for opening a PR. Before I review:
- update the PR to pass CI
- minimize the changes to only what is necessary for the feature. There are a lot of extra files, a package manager change, and directory changes that are unnecessary.

2022-08-19 06:54 UTC, dnim commented
@coston hey! 
can you please take a look on this error? https://app.netlify.com/sites/json-to-csv-export/deploys/62ff2c0ee8a7ea00075ace02
I never worked before with `mdx-go` and `netlify`, so maybe it's something obvious for you. Already spent couple of hours on this. 

If no - I'll take a look deeper. 
Thanks!

2022-08-22 21:12 UTC, coston commented
@dnim There are many changes, like bumping mdx-go a major version, `yarn` to `npm`, and `/dist` to `/built` that are unnecessary for your PR. 

Please simplify the PR to the minimal essentials for:
1. Updating the lib to TS
2. changed signature 
3. Testing ❤️
4. Docs update

2022-08-26 15:43 UTC, dnim commented
@coston should be better now!

2022-08-29 17:15 UTC, coston requested changes
Looks great! Some suggestions and minor changes requested.

2022-08-29 17:15 UTC, coston commented on migration.md
> +## Reason for migration
```suggestion
## Breaking Changes
```

2022-08-29 17:15 UTC, coston commented on migration.md
> +New version was written in TS and a bit changed the arguments list to make it more convenient and flexible
```suggestion
Named parameters are now required for passing custom `data`, `filename`, and `delimeter` props. 
```

2022-08-29 17:15 UTC, coston commented on migration.md
> +New version was written in TS and a bit changed the arguments list to make it more convenient and flexible
How filenames are handled should be mentioned too.

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +    : 'export.csv'
Please no nested ternaries.

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +    : 'export.csv'
Just set `export.csv` at the top (like the delimeter) for visibility.

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +  filename, // default to 'export.csv'
```suggestion
  filename = 'export.csv',
```

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +  filename, // default to 'export.csv'
See my comments on filename below.

2022-08-29 17:15 UTC, coston commented on migration.md
> +New version was written in TS and a bit changed the arguments list to make it more convenient and flexible
Removal of IE msSaveBlob support should be mentioned.

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +      .map((fieldName) => JSON.stringify(row[fieldName] ?? ''))
Zero handling needs to be restored https://github.com/coston/json-to-csv-export/pull/29/files

2022-08-29 17:15 UTC, coston commented on test/index.spec.ts
> +describe("csvDownload", () => {
Thank you for this!

2022-08-29 17:15 UTC, coston commented on src/index.ts
> +    ? providedFilename.toLowerCase().endsWith('.csv')
minor comment: I was on the fence about this feature. It's not really needed, but it's nice. Consider using a regex instead, as I think it's faster than the toLowerCase + endsWith combo. 
```suggestion
    ? /csv$/i.test(providedFilename)
```

2022-08-29 17:15 UTC, coston commented on readme.md
> +  headers: ['IP', "Full Name", "# Address"]
```suggestion
  headers: ['IP', "Full Name", "IP Address"]
```

2022-08-29 17:15 UTC, coston commented on package.json
>      "watch": "babel -w -d dist src --copy-files",
Please update this one to watch src changes when running dev

2022-09-13 22:20 UTC, coston approved these changes
Very nice, @dnim! I will make a couple of [nit] tweaks after merging. LGTM! 🚀

2022-09-13 22:20 UTC, merged