Added support for Header Mapping
coston/json-to-csv-export pull request #72
Opened 2024-10-01 20:38 UTC by amirGaouaou

Added an extra option for Headers 

```typescript
interface HeaderMapping {
  label: string;
  key: string;
}
```

See example here

```jsx
// import jsonToCsvExport from "json-to-csv-export";
  const mockData = [
    {
      id: 1,
      firstName: "Sarajane",
      lastName: "Wheatman",
      email: "swheatman0@google.nl",
      language: "Zulu",
      ip: "40.98.252.240",
    },
    {
      id: 2,
      firstName: "Linell",
      lastName: "Humpherston",
      email: "lhumpherston1@google.com.br",
      language: "Czech",
      ip: "82.225.151.150",
    },
  ];

  const headers = [
    { key: "id", label: "Identifier" },
    { key: "firstName", label: "First Name" },
    { key: "lastName", label: "Last Name" },
    { key: "email", label: "Email Address" },
    { key: "language", label: "Language" },
    { key: "ip", label: "IP Address" },
  ];

  return (
    <button onClick={() => jsonToCsvExport({ data: mockData, headers })}>
      Download Data
    </button>
  );
```

2024-10-01 20:53 UTC, zachelrath requested changes
This is a great feature addition @amirGaouaou ! 🙌🏽 Very useful to be able to retain original data row property names while still having custom header column names.

Overall looks great, just saw a small issue with the runtime preview and some other minor things.

2024-10-01 20:53 UTC, zachelrath commented on test/index.spec.ts
> +    console.log(generatedCsvString);
@amirGaouaou can you remove this console log?

2024-10-01 20:53 UTC, zachelrath commented on src/generate.ts
> -      /* RFC-4180
Was the removal of this comment intentional?

2024-10-01 20:53 UTC, zachelrath commented on README.md
> +  );
This example isn't rendering correctly at runtime, needs to be wrapped in a function:
```suggestion
() => {
  const mockData = [
    {
      id: 1,
      firstName: "Sarajane",
      lastName: "Wheatman",
      email: "swheatman0@google.nl",
      language: "Zulu",
      ip: "40.98.252.240",
    },
    {
      id: 2,
      firstName: "Linell",
      lastName: "Humpherston",
      email: "lhumpherston1@google.com.br",
      language: "Czech",
      ip: "82.225.151.150",
    },
  ];

  const headers = [
    { key: "id", label: "Identifier" },
    { key: "firstName", label: "First Name" },
    { key: "lastName", label: "Last Name" },
    { key: "email", label: "Email Address" },
    { key: "language", label: "Language" },
    { key: "ip", label: "IP Address" },
  ];

  return (
    <button onClick={() => jsonToCsvExport({ data: mockData, headers })}>
      Download Data
    </button>
  );
  };
```
<img width="767" alt="Screenshot 2024-10-01 at 4 47 48 PM" src="https://github.com/user-attachments/assets/62b47820-5fd4-4b42-bc2c-4655cfa03688">

2024-10-01 20:53 UTC, zachelrath commented on README.md
> +| 4 | headers   | string[] OR<br />HeaderMapping[] | optional    | provided data object keys | List of columns that will be used in the final CSV file. Recommended for large datasets! |
The `<br/>` is getting rendered literally as text in the preview. Might not be worth it here, can probably just leave it out.

2024-10-01 23:24 UTC, zachelrath approved these changes
Latest changes look good to go, LGTM! ✅

2024-10-02 14:16 UTC, coston approved these changes
@amirGaouaou this looks really good. Thank you for your contribution!

@zachelrath thank you for reviewing!

2024-10-02 14:17 UTC, merged